### ISSUE TITLE
Picture in picture rendering for multiple predicates

### ISSUE THREAD

**Issue by subsoap** [britzl/lumiere#6]
Something I want is the ability to render specific scenes within rectangles (as in cutting off the sides outside of a rectangle) using multiple 3d cameras. Manually setting this up in like rendercam is a bit of a pain. It can be useful for drawing 3d characters on top of other assets. 

![ucf9hi12rx931](https://user-images.githubusercontent.com/409170/80299502-b824c000-8749-11ea-884c-dbdafd03b97c.jpg)

This is a kind of thing that would be useful to be able to do. I've thought about ways to do this properly and it all seems like a pain to me.

Another thing is imagine 3 windows looking into 3 different 3d scenes. It is currently possible to do but requires custom render script, maybe it could be made simple and easy.

**Comment by britzl** [comment]
Lumiere has changed direction since this issue was created. Lumiere is now only for applying post processing effects. Closing this issue.
